/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package src.lambda

import com.amazonaws.services.lambda.runtime.Context
import com.amazonaws.services.lambda.runtime.RequestHandler

class HandlerInput {
    var message: String = ""
    var sourceLangCode: String = "en"
    var targetLangCode: String = ""
}

data class HandlerOutput(
        val translatedText: String?
)

class TranslatorHandler : RequestHandler<HandlerInput, HandlerOutput> {
    override fun handleRequest(input: HandlerInput?, context: Context?): HandlerOutput {

        val awsTranslator = AwsTranslator()

        val response = input?.let {
            awsTranslator.translate(input.message, input.sourceLangCode, input.targetLangCode)
        }

        return HandlerOutput(response?.translatedText())
    }
}