/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package src.lambda

import com.amazonaws.services.lambda.runtime.Context
import com.amazonaws.services.lambda.runtime.RequestHandler
import java.util.*

class HandlerInput {
    var successful: Boolean = false
    var translatedText: String = ""
}

class HandlerOutput

class S3Handler : RequestHandler<HandlerInput, HandlerOutput> {

    override fun handleRequest(input: HandlerInput?, context: Context): HandlerOutput {

        val s3 = S3()

        input?.let {

            if(input.successful) {
                context.logger.log(
                        "Successful translation, storing in S3."
                )
                s3.uploadToS3(UUID.randomUUID(), it.translatedText)
            } else {
                context.logger.log("Failed to Translate, not storing anything in S3")
            }
        }

        return HandlerOutput()
    }

}